[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["gymnasium_env_gaze"]

[project]
name = "gymnasium_env_gaze"
version = "0.0.1"
dependencies = [
  "gymnasium",
  "pre-commit",
]
